version: "3.8" # Ensure this version is compatible with your Docker setup

services:
  # postgres:
  #   image: postgres:16
  #   restart: always
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - /postgres-data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 10s
  #     retries: 5

  # backend:
  #   build: ./backend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules
  #   healthcheck:
  #     test: ["CMD-SHELL", "nc -z localhost 5432"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 10
  #   environment:
  #     PG_CONNECTION_STRING: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "3001:80"
    # depends_on:
    #   - backend
